### ISSUE TITLE
Title attribute doesnt render HTML tags.

### ISSUE THREAD

**Issue by hariesnurikhwan** [afzafri/UiTM-Timetable-Generator#1]
![image](https://cloud.githubusercontent.com/assets/10152692/14572681/aa5dcf92-0382-11e6-8deb-5301b77618a2.png)

**Comment by shahril96** [comment]
Hi Haries,

Looks like I missed this one haha. Well I just made a quick patch to fix this where I removed the title attribute and its value completely from timetable.js renderer.

Thanks for reporting!
