### ISSUE TITLE
Website is inaccessible.

### ISSUE THREAD

**Issue by Dolpheyn** [afzafri/UiTM-Timetable-Generator#11]
uitmtimetable.com is out of reach. Is there a way to use the program locally on my pc?

![uitmtimetable-host-error](https://user-images.githubusercontent.com/47665123/52911791-cd9b9000-32e3-11e9-8182-1ac4a83c6023.jpg)

**Comment by Dolpheyn** [comment]
Course registration day is coming and finding the class with the best timetable using icress is just.. a bad experience.  So it would be great if you guys fix the website :)

**Comment by afzafri** [comment]
Hi there, yes the website is down since we have no funds to pay the web server fees. 
Yes, you can use the program locally on your pc by installing XAMPP in order to create a local web server. You can then download the source code from this repository, and drop it into your XAMPP htdocs directory.

**Comment by aqmalafiq** [comment]
btw if you are interested for cheap webserver fee can pm me cuz i also use your timetable hahaha

**Comment by shahril96** [comment]
For the time being, you can use this "old" version that was hosted here:

https://pahang.uitm.edu.my/UiTM-Timetable-Generator/

Previously, our hosting and domain were donated by this anonymous generous guy. I will find an alternative soon and hopefully come out with new hosting and domain.

**Comment by shahril96** [comment]
Good news.

The previous donator agreed to donate for another one year for this service.

I have configured the server and now it is running up good again in uitmtimetable.com.

Have fun!

**Comment by Dolpheyn** [comment]
That was quick.

You just saved a lot of time for lots of students. Thanks guys!
