### ISSUE TITLE
Tukar fungsi Php

### ISSUE THREAD

**Issue by AlexanderEric** [afzafri/UiTM-Timetable-Generator#15]
<!DOCTYPE html>
<html>
<style>
table,th,td {
  border : 1px solid black;
  border-collapse: collapse;
}
th,td {
  padding: 5px;
}
</style>
<body>

<button type="button" onclick="loadXMLDoc()">Load Time Table</button>
<br><br>
<table id="demo"></table>

<script>
function loadXMLDoc() {
  var xmlhttp = new XMLHttpRequest();
  xmlhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
      myFunction(this);
    }
  };
  xmlhttp.open("GET", "cd_catalogttuitm.xml", true);
  xmlhttp.send();
}
function myFunction(xml) {
  var i;
  var xmlDoc = xml.responseXML;
  var table="<tr><th>CLASS</th><th>COURSE</th><th>TIME</th></tr>";
  var x = xmlDoc.getElementsByTagName("CD");
  for (i = 0; i <x.length; i++) { 
    table += "<tr><td>" +   
    x[i].getElementsByTagName("CLASS")[0].childNodes[0].nodeValue +
    "</td><td>" +
    x[i].getElementsByTagName("COURSE")[0].childNodes[0].nodeValue +
    "</td><td>" +
	x[i].getElementsByTagName("TIME")[0].childNodes[0].nodeValue +
    "</td></tr>";
  }
  document.getElementById("demo").innerHTML = table;
}
</script>
</body>
</html>

**Comment by AlexanderEric** [comment]
FORMAT PHP TIDAK WUJUD 
terima kasih...

**Comment by AlexanderEric** [comment]
https://github.com/AlexanderEric/IRIS
<<sample format asas yang aku tahu, boleh try download, unzip, start
Asas

**Comment by shahril96** [comment]
What?

**Comment by shahril96** [comment]
Question is ambiguous and poorly formatted.

Re-open if you think this is necessary.
