### ISSUE TITLE
Domain unresolved, possibly because of expired domain name.

### ISSUE THREAD

**Issue by alzhahir** [afzafri/UiTM-Timetable-Generator#23]
The website https://www.uitmtimetable.com no longer resolve to the web host containing the actual timetable application. I hope that the website maintainer could host the site for much longer since a lot of people rely on this service.

However I understand why the service wasn't maintained any longer because of cost or time issues.

**Comment by ADIBzTER** [comment]
Hi @alzhahir. I have deployed the latest one on heroku due to expiration of uitmtimetable.com. Here the link [https://uitmtimetable.herokuapp.com/](https://uitmtimetable.herokuapp.com)
