### ISSUE TITLE
MAT 525 wont load at schedule

### ISSUE THREAD

**Issue by aimanova4** [afzafri/UiTM-Timetable-Generator#26]
cawang negeri sembilan 
bila dah pilih subjek n class
ada keluar error mcm ni
RangeError: Timetable scope should consist of (start, end) in whole hours from 0 to 23

**Comment by ADIBzTER** [comment]
Hi @aimanova4. boleh saya tahu anda guna website yang mana? Sebab domain [uitmtimetable.com](https://uitmtimetable.com) dah expired.

**Comment by aimanova4** [comment]
saya pkai yg ni UiTM Timetable Generator
<https://pahang.uitm.edu.my/UiTM-Timetable-Generator/> ,sbb dari diploma
smpai hujung degree tiada masalah, cuma sem ni subjek tu je yg problem tiba2

**Comment by ADIBzTER** [comment]
@aimanova4 Cuba pakai yang ini [https://uitmtimetable.herokuapp.com](https://uitmtimetable.herokuapp.com/). Ni yang latest
