### ISSUE TITLE
Search inside selectbox.

### ISSUE THREAD

**Issue by shahril96** [afzafri/UiTM-Timetable-Generator#3]
Because the data inside select-box can contain thousand of courses, it's better to provide searching functionality for the select-box.

**Comment by shahril96** [comment]
This gonna be hard to implement because by changing the select box to using another class, we need to reinvent the javascript auto selector and dynamic timetable back.

**Comment by afzafri** [comment]
Enhancement added. Used a JavaScript plugin '[blob-select](https://github.com/Blobfolio/blob-select)' to add the searching functionality for the select-box.
Commits: https://github.com/afzafri/UiTM-Timetable-Generator/commit/a42ed07fc572fd0de4b519caab004024a1665fc3, https://github.com/afzafri/UiTM-Timetable-Generator/commit/9dc75cbf1b1c1cebb452d942d9a046f3de280ace, https://github.com/afzafri/UiTM-Timetable-Generator/commit/90e8ac6b3c4bc9c5839a33f3e8bfaa912a8bd492, https://github.com/afzafri/UiTM-Timetable-Generator/commit/86215ebd5e15341210893e7ad5a99fcbaf18210f
