### ISSUE TITLE
subj MEC241(FLUID DYNAMICS) di UiTM PENANG TIADA 

### ISSUE THREAD

**Issue by babyboaa** [afzafri/UiTM-Timetable-Generator#32]
i nak susun but theres a missing subj

**Comment by ADIBzTER** [comment]
Hi @babyboaa. Cuba guna https://uitmtimetable.herokuapp.com. Saya cek subjek MEC241, ada keluar. Ni official website untuk projek ni buat masa ni.

**Comment by babyboaa** [comment]
owhh tadi tak dak.. tiba2 ada.. thank you
