### ISSUE TITLE
problem with timetable generator

### ISSUE THREAD

**Issue by Balo45** [afzafri/UiTM-Timetable-Generator#39]
there's no list of campusses that i can pick to build my timetable can u fix this issue asap

**Comment by ADIBzTER** [comment]
May I know which site were you using? The official one is https://uitmtimetable.herokuapp.com

**Comment by KesunyianAyam** [comment]
as of now, it's affecting the official site

**Comment by ADIBzTER** [comment]
@KesunyianAyam Thanks for the update. I realized icress often being put in maintanence mode when they are updating the timetable. I'll try to notify users when this happen. Thanks again.
