### ISSUE TITLE
TIME TABLE ERROR

### ISSUE THREAD

**Issue by fitrijamil** [afzafri/UiTM-Timetable-Generator#44]
hi nak tanya kenapa bila nk letak nama subjek dengan kelas dia  keluar "RangeError: Timetable scope should consist of (start, end) in whole hours from 0 to 23"

**Comment by ADIBzTER** [comment]
You need to clear your browser's cache. Please let me know if it works

**Comment by fitrijamil** [comment]
okay dah boleh ..thanks
