### ISSUE TITLE
timetable problem

### ISSUE THREAD

**Issue by ainsna003** [afzafri/UiTM-Timetable-Generator#45]
jadual tu tak keluar walaupun dah masukkan subjek dan kelas 

RangeError: Timetable scope should consist of (start, end) in whole hours from 0 to 23 

dia cakap gitu

**Comment by ADIBzTER** [comment]
Cuba clear browser cache dan try balik. Kalau okay, bagitau. Kalau still tak boleh pon bagitau.

**Comment by Kiee003** [comment]
still sama

**Comment by ainsna003** [comment]
sama jugak tak boleh keluar jadualnya , kalini takboleh masukkan nama u pun , subjek semua takde pilihan untuk pilih pun , kosong je

**Comment by ajeeq** [comment]
For temporary solution, can use mobile android app version [UiTM Scheduler](https://play.google.com/store/apps/details?id=com.ajeeq.uitmscheduler) (still in beta - early access) that features vertical timetable and course time clash detection same as this UiTM Timetable.

**Comment by afzafri** [comment]
Should be fixed in https://github.com/afzafri/UiTM-Timetable-Generator/commit/916766aa5ab0e5bfc01193eabad56bc115dc6ebd . @ADIBzTER bila free tolong pull dalam heroku. thanks
