### ISSUE TITLE
The list of campus don’t appear 

### ISSUE THREAD

**Issue by Aiemanhziq** [afzafri/UiTM-Timetable-Generator#46]
Hi, I'm writing to inform you that the list of campuses doesn't show up even though I have already inserted the campus name manually.

**Comment by ajeeq** [comment]
For temporary solution, can use mobile android app version [UiTM Scheduler](https://play.google.com/store/apps/details?id=com.ajeeq.uitmscheduler) (still in beta - early access) that features vertical timetable and course time clash detection same as this UiTM Timetable.
