### ISSUE TITLE
nothing show up on the search engine

### ISSUE THREAD

**Issue by echaejel** [afzafri/UiTM-Timetable-Generator#47]
im soorry to distrub you but there seem to be a problem with this timetable uitm, whenever i try type on the search engine, its not working. please fix this

**Comment by ajeeq** [comment]
For temporary solution, can use mobile android app version [UiTM Scheduler](https://play.google.com/store/apps/details?id=com.ajeeq.uitmscheduler) (still in beta - early access) that features vertical timetable and course time clash detection same as this UiTM Timetable.
