### ISSUE TITLE
kenapa list subject tak keluar

### ISSUE THREAD

**Issue by husna187** [afzafri/UiTM-Timetable-Generator#48]

**Comment by ajeeq** [comment]
For temporary solution, can use mobile android app version UiTM Scheduler (still in beta - early access) that features vertical timetable and course time clash detection same as this UiTM Timetable.

**Comment by afzafri** [comment]
Should be fixed in https://github.com/afzafri/UiTM-Timetable-Generator/commit/916766aa5ab0e5bfc01193eabad56bc115dc6ebd . @ADIBzTER bila free tolong pull dalam heroku. thanks
