### ISSUE TITLE
There is an error when doing an Ajax request! HTTP Error Code :500

### ISSUE THREAD

**Issue by Brighttitaness** [afzafri/UiTM-Timetable-Generator#49]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/115444224/194800407-0c433706-06cc-49f9-87ac-8b1d4e13b64e.png">

An error appeared when the campus is selected. After selecting the campus, subjects wouldn't appear and neither does the groups

**Comment by ADIBzTER** [comment]
@afzafri bro diorang tukar url lagi hahaha. Memang taknak bagi kita scrap ni. Jap lagi aku fix

**Comment by ADIBzTER** [comment]
c7370c03cdf52fb7d5c490adf66026a2d0d089f7 fixed this
