### ISSUE TITLE
No subjects

### ISSUE THREAD

**Issue by Brighttitaness** [afzafri/UiTM-Timetable-Generator#50]
### [
![IMG_20221013_105318](https://user-images.githubusercontent.com/115444224/195488266-b8ccf712-e220-42ce-965a-6e9c8a0be03b.jpg)
](url)

**Comment by KesunyianAyam** [comment]
i second this issue

**Comment by ADIBzTER** [comment]
41398885cdab43c24c8588462444eaa90fc12a13 fixed this
