### ISSUE TITLE
chmod 777 is dangerous for security reasons

### ISSUE THREAD

**Issue by KesunyianAyam** [afzafri/UiTM-Timetable-Generator#53]
I would like to propose an update to the README.md for the installation part.

As we all know, 777 is a very dangerous permission. Refer https://askubuntu.com/questions/20105/why-shouldnt-var-www-have-chmod-777

I've googled some suggestions and my findings are:

- To change permissions of directories to 755: `find /path/to/UiTM-Timetable-Generator/ -type d -exec chmod 755 {} \;`

- To change permissions of files to 644: `find /path/to/UiTM-Timetable-Generator/ -type f -exec chmod 644 {} \;`

- To change permissions of all .php files to 600: `find /path/to/UiTM-Timetable-Generator/ -name *.php -exec chmod 600 {} \;`

Source:

1. https://stackoverflow.com/questions/3740152/how-do-i-change-permissions-for-a-folder-and-its-subfolders-files
2. https://help.krystal.uk/web-hosting/what-file-and-directory-permissions-should-i-use-for-my-web-files

**Comment by afzafri** [comment]
Hi, thank you for the suggestion. Feels free to do a pull request. Thanks

**Comment by afzafri** [comment]
Closing this issue. Updated Readme with suggestion in https://github.com/afzafri/UiTM-Timetable-Generator/commit/a6a77d5f85636c2d3a894266e5d5ff4c33fa8a7f
Thanks
