### ISSUE TITLE
UiTM Timetable Generator: Blank

### ISSUE THREAD

**Issue by 25lyari** [afzafri/UiTM-Timetable-Generator#57]
There's no option for selecting a campus or the subject and group.

**Comment by ADIBzTER** [comment]
Hey there, thanks for reporting this issue. I have verified this issue is valid. Will fix it soon

**Comment by ADIBzTER** [comment]
lol. It's working now. Maybe icress was down or something. @25lyari if it works on your side, feel free to close this issue. thanks

**Comment by ADIBzTER** [comment]
Any issue related to icress will be tracked here #58
