### ISSUE TITLE
UiTM TIMETABLE GENERATOR ERROR

### ISSUE THREAD

**Issue by iqin04** [afzafri/UiTM-Timetable-Generator#58]
can't choose subject and group #57

**Comment by Zulaikha028** [comment]
the timetable doesn't show the subject and group. Please fix it quickly so we (students) can refer our classes

**Comment by ADIBzTER** [comment]
Hey there, thanks for reporting. It seems ICReSS is behaving weirdly. That's why you got that bug. I'll keep my eyes on this issue and see what we can do on our side.

**Comment by ADIBzTER** [comment]
ICReSS is back to normal. Nothing need to be done on our end.
