### ISSUE TITLE
Problem with the campus/faculty selection

### ISSUE THREAD

**Issue by Mafiakidal** [afzafri/UiTM-Timetable-Generator#61]
i dont know if the website is still actively maintained but this problem made the whole website broken. Cant choose campus means cant choose subject to key in the timetable.

**Comment by ADIBzTER** [comment]
Hey there, thanks for reporting. Will look into this issue. BTW, is it a new semester already for UiTM?

**Comment by Mafiakidal** [comment]
now still sem break

**Comment by Mafiakidal** [comment]
damn..everything works fine...thx

**Comment by Mafiakidal** [comment]
![prob ](https://github.com/afzafri/UiTM-Timetable-Generator/assets/60030818/52f2d3b7-c941-4aac-acb2-8fe20a253372)

the subject key-in functionality still not working..the campus part works btw

**Comment by ADIBzTER** [comment]
For the time being, please use [iCress](https://simsweb4.uitm.edu.my/estudent/class_timetable/index.htm) (they renamed it to Class Timetable?). I don't have enough capacity to fix this for now. Hope other contributors will help to fix this soon.

Just in case any contributor stop by, please refer #60

**Comment by adibzter** [comment]
Fixed in #62
