### ISSUE TITLE
group problem

### ISSUE THREAD

**Issue by mdanzed** [afzafri/UiTM-Timetable-Generator#63]
group for subject not appear after entered the course

**Comment by adibzter** [comment]
@mdanzed It Sounds like a temporary failure from icress side. Please try again and let us know if the issue persists.

**Comment by adibzter** [comment]
Hey @mdanzed, is it working now?

**Comment by nadeem126** [comment]
I'm having the same problem since yesterday and it's not working yet.

**Comment by adibzter** [comment]
Fixed on #75
