### ISSUE TITLE
Select Subject Issues 

### ISSUE THREAD

**Issue by medkeither** [afzafri/UiTM-Timetable-Generator#66]
![Screenshot_2024-03-17-14-21-48-98_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/afzafri/UiTM-Timetable-Generator/assets/163712005/5d09740b-07ed-4374-8c7c-e297754ccdf5)

Hi can you help with this? I've been trying for like almost 4 days and it keep appearing like this. I have tried on my laptop too and nothing have changed. I've tried refreshing the website too but it's still the samw

**Comment by adibzter** [comment]
Hi @medkeither, may I know which campus this is? 

In the meantime, could you try again? I think it's a temporary error from icress

You can also go straight to the official timetable https://simsweb4.uitm.edu.my/estudent/class_timetable/index.htm

**Comment by adibzter** [comment]
Fixed on #75
