### ISSUE TITLE
MISSING CLASS IN TIMETABLE

### ISSUE THREAD

**Issue by iqqkhai** [afzafri/UiTM-Timetable-Generator#71]
Uitm rembau, there are missing class in subject FIN250 for N5BA1193A it should have 8 - 10 on monday and ECO211 10 - 12 on monday too. Please help to fix this

**Comment by adibzter** [comment]
@iqqkhai thanks for reporting. Indeed it is a bug

**The appear in icress**
![image](https://github.com/afzafri/UiTM-Timetable-Generator/assets/35218502/d476e64d-edd3-453e-8fb3-016aa34144f5)

**Does not appear in the UI**
![image](https://github.com/afzafri/UiTM-Timetable-Generator/assets/35218502/1b0de544-0bc6-4eb6-b05e-126965d24da9)

**Does not even appear in the network tab**
![image](https://github.com/afzafri/UiTM-Timetable-Generator/assets/35218502/4511c1c9-4ee5-4eb1-b997-1e975bb2bbcf)

**Comment by adibzter** [comment]
Fixed on #75
