### ISSUE TITLE
Need a Remove Button

### ISSUE THREAD

**Issue by Matter-Shifter** [afzafri/UiTM-Timetable-Generator#8]
A 'remove subject' button needed instead of leaving the wrong subject just like that. It could be needed to make it more user-friendly.

**Comment by shahril96** [comment]
Hi @Matter-Shifter, yeah good idea, it should be easier to handle for mobile users too. I'll take a look into this. Thanks!

**Comment by shahril96** [comment]
Commit 2aec663d477f637d33f080a0f70904c4979426c5 implemented this functionality. It should be anywhere up tomorrow on the official website.
