### ISSUE TITLE
AutoFetch won't work if the student havent completed SuFO

### ISSUE THREAD

**Issue by hollowsxd** [afzafri/UiTM-Timetable-Generator#9]
AutoFetch cannot fetch data from iLearn from the course menu because the menu get blocked if the student havent complete the SuFO survey

**Comment by shahril96** [comment]
Hi @hollowsxd, sorry for late reply!

Yes logically it will not fetch any data as the system redirected the interface to SuFO if it detect that the subject's sufo hasn't been completed yet.

I can't investigate as right now the istudent is down, but I will later when the system up again.

Thanks for reporting!

**Comment by shahril96** [comment]
I have investigated the problem.

There is currently no way for us to "bypass" the SuFO and proceed directly with auto-fetcher. Maybe there is a way, but currently, I don't know any.

I've added a checking 963026b85550776e049dbd078a2e5ca863936e91 that will report an error if student still not completed his/her SuFO yet. Hope this will somehow partially fixes this problem.

Cheer.
